import '../assets/styles/font.css';
import './global.css';

import { AuthProvider } from '../features/auth/auth-provider';

export const metadata = {
	title: 'NFT Marketplace',
	description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body suppressHydrationWarning>
				<AuthProvider>{children}</AuthProvider>
			</body>
		</html>
	);
}
