import '../assets/styles/font.css';
import './global.css';

import { Footer } from './(main)/layout/footer';
import { Header } from './(main)/layout/header';

export const metadata = {
  title: 'NFT Marketplace',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
